# Generated by Django 3.2.11 on 2022-01-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='provider_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_basic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('midelname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('last_snn', models.IntegerField(max_length=4)),
                ('dob', models.DateField()),
                ('phone_h', models.CharField(max_length=15)),
                ('phone_w', models.CharField(max_length=15)),
                ('phone_m', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=25)),
                ('mail_address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=15)),
            ],
        ),
    ]
