# Generated by Django 3.2.11 on 2022-01-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_basic',
            name='dob',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='user_basic',
            name='last_snn',
            field=models.CharField(max_length=4),
        ),
    ]
