# Generated by Django 3.2.11 on 2022-01-17 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0002_auto_20220117_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('midelname', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
                ('last_snn', models.CharField(max_length=4)),
                ('dob', models.DateField(default=0)),
                ('phone_h', models.CharField(max_length=15)),
                ('phone_w', models.CharField(max_length=15)),
                ('phone_m', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=25)),
                ('mail_address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user_basic',
        ),
    ]
